### ISSUE TITLE
Photo selection is not attributed to logged-in users

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#4338] opened 2021-10-30 06:32 UTC
### What
Photo attribution is inconsistant based on the queries made by the app
### Screenshot
![image](https://user-images.githubusercontent.com/1689815/139523044-37df45b9-ffc7-42a7-9ae5-9e1c650b3305.png)
### Part of

**Comment by g123k** [comment] 2022-03-19 12:33
I have checked this issue and I think the problem is not from the app itself.
Basically, a call to `/cgi/product_image_upload.pl` is made with valid `user_id` and `password` fields.

I will post an issue on the dedicated repo

**Comment by teolemon** [comment] 2022-03-19 12:55
We should probably have a test for successful attribution on openfoodfacts-dart

**Comment by stephanegigandet** [comment] 2022-03-21 17:38
So from the screenshot attached (is that from the app?) it's not image upload that is not attributed, it's the photo selection / cropping. It also needs the user_id + password fields to be sent.

**Comment by g123k** [comment] 2022-03-25 13:08
This issue should be resolved in the latest release

**Closed as completed by g123k** 2022-03-25 13:08 UTC
Labels: help wanted, quality of contributions, contribution, image upload
