### ISSUE TITLE
IllegalArgumentException while opening edit

### ISSUE THREAD

**Issue by mrudultora** [openfoodfacts/openfoodfacts-androidapp#3751] opened 2021-01-17 07:03 UTC
**Describe the bug**
When trying to open edit the app crashes as the value is neither 100g nor serving.

**To Reproduce**
1. Search _Peanut Butter_
2. Open product at 5th position
3. Click on edit in SummaryFragment

**Expected behavior**
ProductEditActivity must open.

**Screenshots**

**Comment by mrudultora** [comment] 2021-01-17 07:04
I have fixed this issue. Will make a PR soon.

**Comment by mrudultora** [comment] 2021-01-18 10:29
@VaiTon Sometimes the value passed is _100.0 g_. As the **value** is final I cannot convert 100.0 g to 100g. So, I created a new constant for 100.0 g. Is it the correct way ?

**Comment by VaiTon** [comment] 2021-01-18 10:31
@mrudultora I'm sorry it is not. I've already created an issue but i can't seem to find it. @teolemon do you remember this issue?

**Comment by mrudultora** [comment] 2021-01-18 10:36
@VaiTon That's why I asked you before creating a PR. Could you suggest me a way to do so. Because declaring the value as _var_ instead of _val_ is also the wrong way.

**Comment by VaiTon** [comment] 2021-01-18 18:37
It's an error with the server, not the application. We just have to wait for them

**Comment by mrudultora** [comment] 2021-01-18 18:46
Okay I am closing this issue :)

**Comment by mrudultora** [comment] 2021-02-09 07:51
@teolemon Its an issue from server side as stated by **VaiTon**. Please have a look into this.

**Comment by TimMagee** [comment] 2021-08-05 14:24
> It's an error with the server, not the application.

The bug reported is a crash in the application. Even if this crash only occurs after a malformed response from the server, the crash is still a bug in the application. Separately we may need to file a bug report against the server. However, the app should not crash. That is very poor user experience and results in users saying the app is "broken". If the app displayed a helpful error message to the user, such as, "Bad response from server", then at least the user would know what went wrong and the user could continue using the functionalities in the app that currently work.

**Comment by teolemon** [comment] 2021-08-07 15:44
I concur @TimMagee, we should have a perfectly working app (at least not crashing) even with the server down.
Would you be able to test the behavior in such cases ? Alternatively, we have a PR up for adoption about offline barcode scan.
For this bug: I'm going to close this one since I can't reproduce it.

**Closed as completed by teolemon** 2021-08-07 15:44 UTC
Labels: editing, NPE
