### ISSUE TITLE
Ability to create list of products

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#163] opened 2016-10-09 14:23 UTC
- Ability to create lists of products from the product page or from the history
- Ability to give them a name
- Ability to export them

**Comment by KarthikRIyer** [comment] 2019-01-14 18:23
@teolemon what does exporting mean here?

**Comment by KarthikRIyer** [comment] 2019-01-17 12:18
@teolemon could you please clarify this issue? I'd like to work on it.

**Comment by serpico** [comment] 2019-02-21 19:41
Duplicate of #2158

**Closed** 2019-03-23 09:36 UTC
Labels: feature, sharing
