### ISSUE TITLE
NPE at ProductEditNutritionFactsFragment

### ISSUE THREAD

**Issue by mrudultora** [openfoodfacts/openfoodfacts-androidapp#3782] opened 2021-01-27 08:07 UTC
**Describe the bug**
Got a npe when coming back from scan to product edit nutrition fragment. 

**To Reproduce**
Attaching the logs
>  java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter view  at openfoodfacts.github.scrachx.openfood.features.product.edit.ProductEditNutritionFactsFragment$ValidTextWatcher.onItemSelected(Unknown Source:2)
        at android.widget.AdapterView.fireOnSelected(AdapterView.java:957)
        at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:946)
        at android.widget.AdapterView.selectionChanged(AdapterView.java:935)

**Comment by kartikaysharma01** [comment] 2021-03-05 23:24
@VaiTon @teolemon This can be closed.
Duplicate of #3854

**Closed as completed** 2021-03-06 14:59 UTC
Labels: editing, NPE
