### ISSUE TITLE
Offline product lookup

### ISSUE THREAD

**Issue by nutpantz** [openfoodfacts/openfoodfacts-androidapp#37] opened 2016-04-17 16:41 UTC
A lot of apps like this I use on my tablet.
And it's on Wi-Fi some of the time but it's usually offline..
Having the ability to save single items, groups of items if not the entire database for extended periods
Of time would be fantastic..

Apps like this can help everyone eat better.And sadly a lot of the people who are challenged the most in proper nutrition don't have regular internet access.

**Comment by itchix** [comment] 2016-04-17 17:04
Duplicate of #30

**Comment by itchix** [comment] 2016-04-17 17:05
Duplicate of #30

**Closed** 2021-04-28 11:42 UTC
Labels: feature, offline, product browsing

**Comment by teolemon** [comment] 2021-08-31 12:06
- Merged into #2069 which has a lot more info
