### ISSUE TITLE
NPE after saving edit

### ISSUE THREAD

**Issue by mrudultora** [openfoodfacts/openfoodfacts-androidapp#3749] opened 2021-01-16 14:26 UTC
**Describe the bug**
The app crashes after selecting the correct arrow in edit (at top right corner).

**To Reproduce**
1. Search _Peanut Butter_
2. Click on 3rd product in the list
3. Click on edit
4. Save by clicking the image at top right corner.

**Expected behavior**
It should save and return to summary fragment.

**Screenshots**
Adding the logs ..
`    java.lang.NullPointerException
        at openfoodfacts.github.scrachx.openfood.features.product.edit.ProductEditIngredientsFragment.getBinding(ProductEditIngredientsFragment.kt:63)
        at openfoodfacts.github.scrachx.openfood.features.product.edit.ProductEditIngredientsFragment.imageLoaded(ProductEditIngredientsFragment.kt:214)
        at openfoodfacts.github.scrachx.openfood.features.product.edit.ProductEditIngredientsFragment.access$imageLoaded(ProductEditIngredientsFragment.kt:61)
        at openfoodfacts.github.scrachx.openfood.features.product.edit.ProductEditIngredientsFragment$loadIngredientsImage$1.onSuccess(ProductEditIngredientsFragment.kt:200)`

**Smartphone (please complete the following information):**
 - Device: [Redmi Note 7S]
 - OS: [ Android 10]

**Comment by kartikaysharma01** [comment] 2021-01-27 18:21
Could not reproduce. @mrudultora Can you clean the project and try again?

**Comment by mrudultora** [comment] 2021-01-27 18:24
@kartikaysharma01 This happened with me approx. 3-4 times. I also tried to reproduce it yesterday, so that I can solve this issue. But I too was unable to reproduce :-(

**Comment by mrudultora** [comment] 2021-01-27 18:25
Also the list might have different product at 3rd position now.

**Comment by kartikaysharma01** [comment] 2021-01-27 18:27
> @kartikaysharma01 This happened with me approx. 3-4 times. I also tried to reproduce it yesterday, so that I can solve this issue. But I too was unable to reproduce :-(

Did you face this issue it with the same product  all the times?

**Comment by kartikaysharma01** [comment] 2021-01-27 18:28
I think this issue can be closed.
@VaiTon @teolemon

**Comment by teolemon** [comment] 2021-07-30 10:19
I'm going to close it, since we don't have the barcode which caused this, and can't reproduce easily. Hopefully (or not), we'll encounter this bug again.

**Closed as completed by teolemon** 2021-07-30 10:19 UTC
Labels: help wanted, editing, NPE
