### ISSUE TITLE
Nutrients list lack of fruits & vegetables estimated percentage

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-androidapp#2554] opened 2019-04-13 07:48 UTC
This information is needed to compute Nutriscore.
It appears in webapp but not in mobile app.

**Comment by teolemon** [comment] 2019-04-18 12:41
Duplicate of https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/1622

**Closed by teolemon** 2019-04-18 12:41 UTC
Labels: nutriscore
