### ISSUE TITLE
Red crosses shown instead of product images

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-androidapp#2895] opened 2019-10-01 08:05 UTC
We have had several reports from users that they can no longer see product images and that instead they have red crosses. They do see images from products that they scanned previously, but not new ones.

First reported by an user on Sept. 10. Galaxy S6 Edge on Android 7.0.

![image](https://user-images.githubusercontent.com/8158668/65944652-7ab9b780-e432-11e9-80e7-9be0d27d5dd9.png)

2 users said the deinstalled and reinstalled the app but that it did not solve the issue.

**Comment by teolemon** [comment] 2019-10-01 09:02
It might be related to cropping @stephanegigandet

**Comment by teolemon** [comment] 2019-10-01 09:02
Or it might be related to an incorrect URL in the app. Either way, we should have more in the logs.

**Comment by stephanegigandet** [comment] 2019-10-01 09:53
I don't have the logs, and it was already quite difficult to get a screenshot, so I don't think I can get the affected users to find and send us the logs.

It's not just one picture, it's all pictures.

**Comment by huzaifaiftikhar** [comment] 2019-10-04 18:48
@teolemon @stephanegigandet I investigated this issue and found out that we use this image only in case there is an error in Picasso while loading the image via the URL that was saved in the DB when the product was viewed. One possible reason could be that the URL is getting stored properly for this user/phone.
For reference see [code](https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/master/app/src/main/java/openfoodfacts/github/scrachx/openfood/views/adapters/HistoryListAdapter.java#L72)

I tried replicating but was not able to reproduce.
![image](https://user-images.githubusercontent.com/10832531/66231878-2bf77080-e705-11e9-8b33-1c3667b47940.png)

**Comment by teolemon** [comment] 2019-10-04 19:05
We should try to refresh the url stored in the database when this is the case (check from the product JSON whether it's still valid)

**Comment by huzaifaiftikhar** [comment] 2019-10-04 19:10
I'm not sure whether this is due to an incorrect URL being stored or a genuine error while loading the image via Picasso for this user/phone.
Refreshing the URL stored in the DB can be implemented when the image fails to load but only once we are sure that this is actually the error.
Is the user able to view the image of these products in the products list view (i.e. after searching for a product by name and not scanning particular one).
Also, can we check with the user if he/she is able to view the product's image in the detailed view of the product?

**Comment by teolemon** [comment] 2020-05-15 12:24
@CharlesNepote is experiencing the issue, and can provide logs.

**Comment by huzaifaiftikhar** [comment] 2020-10-26 07:52
Closed via #3544

**Closed by huzaifaiftikhar** 2020-10-26 07:52 UTC
Labels: Android 7, P1, bug, history, refresh issue
