### ISSUE TITLE
Stop the barcode scanner  from scanning barcodes on product addition

### ISSUE THREAD

**Issue by Baggypants** [openfoodfacts/openfoodfacts-androidapp#3015] opened 2020-02-13 08:29 UTC
**Description**
The barcode scanner remains active while your deciding to add a new product

**Steps to Reproduce**
1. Scan a item 
2. Check barcode. Try to slide up the 'do you want to add a new product' tray, because buttons are clearly no good here, and wave the phone around like a cheap magician with a wand at a childs birthday party.
3. Barcode scanner spots an unrelated barcode due to your flailing. 
4. Enter a product with an entirely unrelated barcode because you checked the barcode once, why would you do that again?

**Smartphone (please complete the following information):**
 - Device:Wileyfox Swift
 - OS: Android
 - Browser Fennic F-Droid
 - Version, of the browser? 68.4.1esr.

**Additional context**
I'm what the kids call a Boomer.

**Comment by teolemon** [comment] 2020-02-19 10:18
Thanks a lot for the report @Baggypants 👍

**Comment by naivekook** [comment] 2021-02-05 16:08
I'll take this

**Comment by naivekook** [comment] 2021-02-10 14:00
hm not really caught what to fix here, I asked a questions in slack https://openfoodfacts.slack.com/archives/C02L15QLA/p1612768303054500, I can return to it after answers or anybody else can take it

**Comment by kartikaysharma01** [comment] 2021-02-12 11:44
If I understand it right, Once the barcode is detected, the camera should be frozen till the BottomSheet is slide down? 
@teolemon @VaiTon

**Comment by VaiTon** [comment] 2021-02-14 12:35
> 
> 
> If I understand it right, Once the barcode is detected, the camera should be frozen till the BottomSheet is slide down?
> @teolemon @VaiTon

Exactly. @teolemon right?

**Comment by kartikaysharma01** [comment] 2021-02-15 06:15
@VaiTon  I'll take this, can you please assign it to me.

**Comment by naivekook** [comment] 2021-02-15 07:06
just copy it here:
I found the issue when your first scan is NOT_FOUND you can't to slide up the bottom panel

**Comment by kartikaysharma01** [comment] 2021-02-15 07:19
@naivekook I am not able to reproduce that or did not understand what you meant. 
I am currently working on the ML scanner so there are gonna be some changes around the continuous scan logic. I have implemented the preview stoppage on bottom panel visible as of now.

**Comment by naivekook** [comment] 2021-02-15 07:32
@kartikaysharma01 I hope this video helps
https://drive.google.com/file/d/16uWcViHmL8IafrvzOGumZmrFqxIZd_g_/view?usp=sharing

**Comment by kartikaysharma01** [comment] 2021-02-15 08:30
> https://drive.google.com/file/d/16uWcViHmL8IafrvzOGumZmrFqxIZd_g_/view?usp=sharing

@naivekook I have fixed this. Will make a PR soon.

**Closed** 2021-03-09 21:12 UTC
Labels: P1, bug, product addition, scanning
