### ISSUE TITLE
Add a continuous scan mode

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#395] opened 2017-01-04 10:15 UTC
![image](https://cloud.githubusercontent.com/assets/1689815/21639191/0cb293a6-d26f-11e6-8632-9784851ad515.png)

- Overlay basic info, and change it whenever a new barcode is detected
- Make it optional

**Comment by huzaifaiftikhar** [comment] 2018-05-23 22:43
Duplicate of #1551

**Closed by huzaifaiftikhar** 2018-05-23 22:43 UTC
Labels: enhancement, feature, scanning
