### ISSUE TITLE
Wrong value in product card

### ISSUE THREAD

**Issue by sashabrava** [openfoodfacts/openfoodfacts-androidapp#3385] opened 2020-08-02 08:50 UTC
**Describe the bug**
When I visit product 5900334005526 from Android app and look at its nutrition facts, it shows wrong value, 49kcal instead of 50, which are set for this product and visible through "edit" tab and website. 

I noticed the issue after I changed product info, but app restart also doesn't solve the issue. Previous value was 55kcal. 

 - Device: Xiaomi Redmi
 - OS: Android 9
 - Version 3.2.9

Opened the product on another Android device, same thing. 

![IMG_1](https://user-images.githubusercontent.com/11160215/89119299-95731780-d4ad-11ea-81cd-59c1cfaf4b9c.jpg)
![IMG_2](https://user-images.githubusercontent.com/11160215/89119300-96a44480-d4ad-11ea-8822-b56bcab52942.jpg)

**Comment by teolemon** [comment] 2020-08-02 12:55
This is a duplicate of https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/2743

**Comment by teolemon** [comment] 2020-08-02 14:55
@sashabrava could you have a look at #2743 ?

**Closed** 2020-08-02 14:54 UTC
Labels: P1, bug, nutrition facts
