### ISSUE TITLE
App crashes upon loading a scanned product or on search by barcode

### ISSUE THREAD

**Issue by lucaa** [openfoodfacts/OpenFoodFacts-androidApp#323] opened 2016-12-03 18:19 UTC
I had this issue on my phone (Samsung S5 mini, Lollipop), on the application installed from the store, but also on the app built locally from sources and deployed in dev mode, on the phone (but also in the simulator)

It reproduced like this:
Case 1:
* open the app
* hit scan
* App says "Loading", after a while application crashes.

Case 2: 
* open the app
* click search by barcode
* type a correct bar code and send
* App says "Loading", after a while the application crashes.

The logs I had in the console, were always similar to this:
```
E/AndroidRuntime: FATAL EXCEPTION: main
                 Process: openfoodfacts.github.scrachx.openfood, PID: 595
                 android.database.sqlite.SQLiteException: no such table: HISTORY_PRODUCT (code 1): , while compiling: SELECT * FROM HISTORY_PRODUCT WHERE barcode = ?
                 #################################################################
                 Error Code : 1 (SQLITE_ERROR)
                 Caused By : SQL(query) error or missing database.
                     (no such table: HISTORY_PRODUCT (code 1): , while compiling: SELECT * FROM HISTORY_PRODUCT WHERE barcode = ?)
                 #################################################################
                     at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                     at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1093)
                     at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:670)
                     at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                     at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
                     at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                     at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                     at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1454)
                     at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1301)
                     at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1172)
                     at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1378)
                     at com.orm.SugarRecord.find(SugarRecord.java:201)
                     at com.orm.SugarRecord.find(SugarRecord.java:187)
                     at openfoodfacts.github.scrachx.openfood.network.OpenFoodAPIClient$1.onResponse(OpenFoodAPIClient.java:109)
                     at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:66)
                     at android.os.Handler.handleCallback(Handler.java:739)
                     at android.os.Handler.dispatchMessage(Handler.java:95)
                     at android.os.Looper.loop(Looper.java:145)
                     at android.app.ActivityThread.main(ActivityThread.java:6938)
                     at java.lang.reflect.Method.invoke(Native Method)
                     at java.lang.reflect.Method.invoke(Method.java:372)
                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

The way I managed to fix it is to:
* clean application cache (on the phone)
* clean application data (on the phone)
* disable instant run in Android Studio ( as indicated by issues #134 and  #44 )

**Comment by lucaa** [comment] 2016-12-05 09:13
I just tested and the fix (cleaning cache & app data and then running in non-instant run) also fixes the problem on the simulator. 

So we will have to study if/how can this project impact the regular users installing the app from the store. If it can, then it might be an important bug to fix.

**Comment by herau** [comment] 2016-12-07 08:44
@lucaa i guess the issue is only appear during dev mode (with instant run).
Do you have test to update locally the sugar version to `master` and keep enable instant run ?

**Comment by lucaa** [comment] 2016-12-08 21:14
> @lucaa i guess the issue is only appear during dev mode (with instant run).

@herau Actually, it seems not. @stephanegigandet just managed to reproduce on his phone, and he never installed this application in dev mode. He had an old version from the playstore (which was crashing when loading a product), then he upgraded to the newest version from the playstore and the issue was still  reproducing.
Then, he cleaned the application cache and application data (as I described above), relaunched the application and everything worked fine.

**Comment by guillaume-uH57J9** [comment] 2016-12-11 17:31
I also encountered some crash using the OFF Android distributed by F-Droid https://f-droid.org/repository/browse/?fdfilter=food&fdid=openfoodfacts.github.scrachx.openfood

The crash occurred when scanning the attached barcode and was easily reproducible by scanning again the same code. 
I was able to scan other barcode without issues/ 
My phone is the Motorolla X 2014 and my Android flavor is CyanogenMod. 

![img_20161130_221805](https://cloud.githubusercontent.com/assets/4953748/21081859/eed68362-bfcf-11e6-9c68-cf542bebf639.jpg)

**Comment by itchix** [comment] 2016-12-13 15:57
Sugar ORM library is really buggy I think. Maybe we have to switch to another one like DBFlow? @herau

**Comment by herau** [comment] 2016-12-14 08:59
@itchix if you want.

**Comment by aleksejrs** [comment] 2017-01-11 10:13
0.4 still crashes (searched by name in Russian, clicked the result).

**Comment by geocohn** [comment] 2017-01-11 15:42
This happens when I use an emulator, and also on some (but not all) phones. I concur with @herau that DBFlow is a good alternative to Sugar ORM.

**Comment by itchix** [comment] 2017-01-11 15:46
I'm testing GreenDAO on a new branch, and it works great for the moment

**Comment by itchix** [comment] 2017-01-23 14:08
Hope 50d9086a53ade10768d02fd8f637adaff802c724 close this issue.
Please open if not

**Closed by itchix** 2017-01-23 14:08 UTC
Labels: bug, question, sql
