### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by ManognaMutyala** [openfoodfacts/openfoodfacts-androidapp#726] opened 2018-02-13 18:07 UTC
App is crashing on clicking information related to products such as ingredients,nutrition,nutrition table

![screenshot_20180213-233214](https://user-images.githubusercontent.com/22299553/36165850-dbed6538-1116-11e8-83f2-940a0c0865e1.png)

**Comment by huzaifaiftikhar** [comment] 2018-02-13 18:24
Not able to reproduce this bug. Works fine on my device.
Android 7.1.1

**Comment by ross-holloway94** [comment] 2018-02-13 18:30
I believe this is a duplicate of #621

**Comment by policorn** [comment] 2018-02-18 01:41
Hi @ManognaMutyala, PR #783 should have fixed it, can you update your repo and try to reproduce it? If it's already fixed please close this issue ticket. Thanks!

**Closed** 2018-02-18 17:31 UTC
Labels: bug, product-browsing

**Comment by policorn** [comment] 2018-02-18 17:40
Thanks @ManognaMutyala!
