### ISSUE TITLE
Display full nutrition table

### ISSUE THREAD

**Issue by moshpirit** [openfoodfacts/OpenFoodFacts-androidApp#99] opened 2016-05-29 08:44 UTC
Something like: calcium, iron, proteins (what amino acids), vitamins (A, C, …), omega (3, 6,…), etc

**Comment by TaciteOFF** [comment] 2016-05-29 08:45
We already provide that when it's on the packaging. 
See http://world.openfoodfacts.org/product/3041090001864/lait-gallia-calisma for instance.

**Comment by moshpirit** [comment] 2016-05-29 09:44
But the table doesn't appear on the Android app, just the ingredients and "Nutrient levels for 100 g" :(

**Comment by itchix** [comment] 2016-05-29 09:49
Yes, I didn't implement it yet

**Comment by moshpirit** [comment] 2016-05-29 09:50
OK, then I leave the issue open :) thanks a lot for this great service!

**Comment by herau** [comment] 2016-09-30 08:39
@itchix does this information should be displayed in another tab ? or in the nutrition tab, after the nutritional mark ?

**Comment by itchix** [comment] 2016-09-30 08:45
I think a new tab is the best, the nutrition tab must be clear. You can add like "Advance nutrition" tab, @teolemon what do you think?

**Comment by teolemon** [comment] 2016-09-30 09:12
Some products will have it, some won't.
So the tab should not be here if there's no advanced information available.

It should be "Advanced Information" or "Advanced Nutrition".

Otherwise you can put it after nutrition and let the user scroll.

**Comment by asmoth360** [comment] 2016-10-01 10:58
Maybe a button at the bottom like "view advanced nutrition" with the information that unfolds ?

**Comment by teolemon** [comment] 2016-10-15 18:15
There are complaints on the Play Store about this. This is legitimate (although I like the synthetic view better) and a regression compared to the current app.

**Comment by teolemon** [comment] 2016-11-04 16:27
Assigned to @Ekt0s

**Comment by itchix** [comment] 2016-11-11 15:02
@teolemon What do you think about that? You can click on the image and then zoom it.
![unnamed 1](https://cloud.githubusercontent.com/assets/2846894/20219129/276a6596-a828-11e6-938b-1b8437539584.png)
![unnamed](https://cloud.githubusercontent.com/assets/2846894/20219125/254d14c0-a828-11e6-97d3-b74e258a7118.png)

**Comment by teolemon** [comment] 2016-11-11 16:30
I'm ok with the zooming, but I wonder about the little circles. It might be an option for those who like it, but I'd very much like a (more synthetic, legible) table approach as well.

**Comment by teolemon** [comment] 2016-11-11 16:36
Here's an extreme example:
http://fr.openfoodfacts.org/produit/3041090001864/lait-gallia-calisma

**Comment by teolemon** [comment] 2016-11-11 16:37
Also, the ability to compare on web is nice, but might be more difficult to achieve (not sure if it's in the JSON, or you have to fetch the Category)

**Comment by itchix** [comment] 2016-11-11 16:55
I don't know if it's a good thing to show the entire table because some phone have a small screen. Display the data may be a little bit small on the screen.
@herau Any idea for the UI?

**Comment by teolemon** [comment] 2016-11-11 16:57
Vertically, it's not a problem (scrolling)
Horizontally, with 100g and categories, agreed.

Please remember that it's nutrition information, and for babies milks and stuff like that, we need to be exhaustive.

**Comment by teolemon** [comment] 2016-11-11 17:15
http://cdn01.androidauthority.net/wp-content/uploads/2015/05/Calorie-Counter-by-MyFitnessPal-screenshot-2016-840x473.jpg

**Comment by herau** [comment] 2016-11-11 17:24
@itchix i like your UI idea. maybe with color level indicator like with 5c.a table is maybe a little bit too simple and austere.

**Comment by teolemon** [comment] 2016-11-11 17:26
uneasy to make nutrition info too playful and not easy to parse quickly. The Nutriscore + the lights are the simple options, the table is the scientific option

**Comment by teolemon** [comment] 2016-11-11 17:28
The FDA imposes a standardized table (black text, white background, same order of nutrients). It's not the case in France.
The whole point of Open Food Facts is having the information in a standardized way, that does not influence you, that is accessible to all (children, blind people…)

**Comment by teolemon** [comment] 2016-11-11 19:16
![screenshot_20161111-173507](https://cloud.githubusercontent.com/assets/1689815/20227213/b063ec46-a84b-11e6-8eae-6704049ed178.png)
Here's the current version

**Comment by herau** [comment] 2016-12-07 14:14
Currently nutriments are not grouped by Fat / Carbohydrate / Proteins / Salt etc (in the API)

So it's complicated to create the same table than in the current open food app.

**Comment by teolemon** [comment] 2016-12-08 11:11
The logic for the table is available in the Food.pm file. It changes from
country to country. Also available are the full text name of the nutrients
plus translations.

**Comment by herau** [comment] 2016-12-08 17:12
ok so we have to define a grid per country i guess.

**Comment by teolemon** [comment] 2016-12-09 00:24
let's stick to one grid, we'll customize later

**Comment by teolemon** [comment] 2017-01-14 10:29
![image](https://cloud.githubusercontent.com/assets/1689815/21954275/ab39f85e-da4c-11e6-8ee9-6ada9ce729da.png)

**Comment by herau** [comment] 2017-01-16 09:43
could be great if you can have sub-division like in the current official OFF app. But currently the API doesn't provide this kind of hierarchy and i think that the division is different per country isn't it @teolemon ?

**Comment by teolemon** [comment] 2017-01-16 09:46
I propose that we copy the structure for English, and localize later (Search is not localized, and the rest of the product page like ingredient list isn't)
Here's a nice example of what subdivisions could look like:
![image](https://cloud.githubusercontent.com/assets/1689815/21977991/ddbb5f88-dbd8-11e6-97ac-39e831adcf60.png)

**Closed** 2017-01-30 11:54 UTC
Labels: bug, enhancement, feature, priority
