### ISSUE TITLE
java.lang.NullPointerExceptionj :    at openfoodfacts.github.scrachx.openfood.utils.Utils.HttpClientBuilder

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1589] opened 2018-05-19 18:06 UTC
Samsung Galaxy Tab A 10.1 (gtaxlwifi), 2048MB RAM, Android 7.0
```

java.lang.NullPointerExceptionj : 
  at openfoodfacts.github.scrachx.openfood.utils.Utils.HttpClientBuilder (Utils.java)
  or                     .apply (Utils.java)
  or                     .bold (Utils.java)
  or                     .compressImage (Utils.java)
  or                     .convertKjToKcal (Utils.java)
  or                     .decodeFile (Utils.java)
  or                     .getAppDaoSession (Utils.java)
  or                     .getBitmapFromDrawable (Utils.java)
  or                     .getClickableText (Utils.java)
  or                     .hideKeyboard (Utils.java)
  or                     .isApplicationInstalled (Utils.java)
  or                     .lambda$scan$0$Utils (Utils.java)
  or                     .openTags (Utils.java)
  at openfoodfacts.github.scrachx.openfood.fragments.SaveOfflineSummaryFragment.b (SaveOfflineSummaryFragment.java:4)
  at openfoodfacts.github.scrachx.openfood.views.SaveProductOfflineActivity.b (SaveProductOfflineActivity.java:8)
  at openfoodfacts.github.scrachx.openfood.views.SaveProductOfflineActivity.onOptionsItemSelected (SaveProductOfflineActivity.java:19)
  at android.app.Activity.onMenuItemSelected (Activity.java:3540)
  at android.support.v4.app.FragmentActivity.onMenuItemSelected (FragmentActivity.java)
  at android.support.v7.app.AppCompatActivity.onMenuItemSelected (AppCompatActivity.java)
  at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected (WindowCallbackWrapper.java:2)
  at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected (WindowCallbackWrapper.java:2)
  at android.support.v7.widget.ToolbarWidgetWrapper$1.onClick (ToolbarWidgetWrapper.java:19)
  at android.view.View.performClick (View.java:6597)
  at android.view.View.performClickInternal (View.java:6574)
  at android.view.View.access$3100 (View.java:778)
  at android.view.View$PerformClick.run (View.java:25881)
  at android.os.Handler.handleCallback (Handler.java:873)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6649)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:826)
```

**Comment by huzaifaiftikhar** [comment] 2018-06-10 10:29
Duplicate of #1658

**Closed by huzaifaiftikhar** 2018-06-10 10:29 UTC
Labels: bug, offline, product addition
