### ISSUE TITLE
country.CountriesWrapperTest > initializationError FAILED

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3640] opened 2020-12-25 20:10 UTC
> Task :app:testObfDebugUnitTest

openfoodfacts.github.scrachx.openfood.models.entities.country.CountriesWrapperTest > initializationError FAILED
    org.junit.runners.model.InvalidTestClassError at ParentRunner.java:525

155 tests completed, 1 failed

**Comment by VaiTon** [comment] 2021-01-01 01:32
Duplicate of #3648.

**Closed as completed by VaiTon** 2021-01-01 01:32 UTC
