### ISSUE TITLE
Crash when accessing the product 3502110004253

### ISSUE THREAD

**Issue by LenaicTerrier** [openfoodfacts/OpenFoodFacts-androidApp#132] opened 2016-08-24 13:26 UTC
The app crash when accessing the product http://world.openfoodfacts.org/product/3502110004253/tropicana-pure-premium-reveil-gourmand either via name search, codebar search or codebar scan.
It's juice sold in France.
The very similar product http://world.openfoodfacts.org/product/3502110003652/reveil-fruite-pure-premium-tropicana on the other hand is fine, no crash.
The app is in french. Got it from F-Droid two days ago (0.2.4)

**Comment by herau** [comment] 2016-09-19 08:14
@LenaicTerrier 
it's works for me via name searching (with token tropicana pure premium réveil gourmand) - **version 2.4.7 Android 5.1.1**

![screenshot_2016-09-19-10-11-34](https://cloud.githubusercontent.com/assets/2950666/18625853/8e879bf0-7e51-11e6-9e7e-e3c9ac378ecb.png)

**Comment by davidak** [comment] 2016-09-25 16:35
may be a duplicate of #104

**Closed** 2016-09-29 19:35 UTC
