### ISSUE TITLE
crash after editing product when saving

### ISSUE THREAD

**Issue by serpico** [openfoodfacts/openfoodfacts-androidapp#2247] opened 2019-02-19 16:57 UTC
**Summary:** 

App crash after editing product when saving

**system logs:**

[logcat.txt.](https://github.com/openfoodfacts/openfoodfacts-androidapp/files/2880986/logcat.txt)

**Expected behavior:** 

What did you expect the app to do?

Show the message "produit envoyé avec succès"

What did you see instead?  OpenFoodFacts has stopped
**Device and Android version:** 
Samsung GT-I9195
Android 4.2.2
App version 2.9.8 from f-droid

I tried with a different phone ( SM-G361F ; Android 5.1.1 ; App version 2.9.8 from f-droid as well ) no problem encountered
**Screenshots:** 

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by teolemon** [comment] 2019-02-19 17:02
```
E/AndroidRuntime(10127): FATAL EXCEPTION: main
E/AndroidRuntime(10127): java.lang.NoClassDefFoundError: java.util.Objects
E/AndroidRuntime(10127): 	at org.a.a.a.d.a(Unknown Source)
E/AndroidRuntime(10127): 	at org.a.a.a.d.a(Unknown Source)
E/AndroidRuntime(10127): 	at openfoodfacts.github.scrachx.openfood.fragments.AddProductOverviewFragment.a(Unknown Source)
E/AndroidRuntime(10127): 	at openfoodfacts.github.scrachx.openfood.fragments.AddProductOverviewFragment.b(Unknown Source)
E/AndroidRuntime(10127): 	at openfoodfacts.github.scrachx.openfood.views.AddProductActivity.x(Unknown Source)
E/AndroidRuntime(10127): 	at openfoodfacts.github.scrachx.openfood.views.AddProductActivity.w(Unknown Source)
E/AndroidRuntime(10127): 	at openfoodfacts.github.scrachx.openfood.views.AddProductActivity.k(Unknown Source)
E/AndroidRuntime(10127): 	at openfoodfacts.github.scrachx.openfood.fragments.AddProductNutritionFactsFragment.next(Unknown Source)
E/AndroidRuntime(10127): 	at openfoodfacts.github.scrachx.openfood.fragments.AddProductNutritionFactsFragment_ViewBinding$10.a(Unknown Source)
E/AndroidRuntime(10127): 	at butterknife.a.a.onClick(Unknown Source)
E/AndroidRuntime(10127): 	at android.view.View.performClick(View.java:4377)
E/AndroidRuntime(10127): 	at android.view.View$PerformClick.run(View.java:18044)
E/AndroidRuntime(10127): 	at android.os.Handler.handleCallback(Handler.java:725)
E/AndroidRuntime(10127): 	at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime(10127): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(10127): 	at android.app.ActivityThread.main(ActivityThread.java:5306)
E/AndroidRuntime(10127): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(10127): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(10127): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
E/AndroidRuntime(10127): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
E/AndroidRuntime(10127): 	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by teolemon** [comment] 2019-02-19 17:10
ava.lang.NoClassDefFoundError: 
  at org.apache.commons.lang3.StringUtils.capitalize (StringUtils.java)
  or                     .containsAny (StringUtils.java)
  or                     .isEmpty (StringUtils.java)
  or                     .join (StringUtils.java)
  or                     .replace (StringUtils.java)
  at org.apache.commons.lang3.StringUtils.capitalize (StringUtils.java)
  or                     .containsAny (StringUtils.java)
  or                     .isEmpty (StringUtils.java)
  or                     .join (StringUtils.java)
  or                     .replace (StringUtils.java)
  at openfoodfacts.github.scrachx.openfood.fragments.AddProductOverviewFragment.access$000 (AddProductOverviewFragment.java)
  or                     .getCountryName (AddProductOverviewFragment.java)
  or                     .getValues (AddProductOverviewFragment.java)
  or                     .hideImageProgress (AddProductOverviewFragment.java)
  or                     .lambda$loadAutoSuggestions$2$AddProductOverviewFragment (AddProductOverviewFragment.java)
  or                     .lambda$selectProductLanguage$3$AddProductOverviewFragment (AddProductOverviewFragment.java)
  or                     .onActivityResult (AddProductOverviewFragment.java)
  or                     .onAttach (AddProductOverviewFragment.java)
  or                     .onCreateView (AddProductOverviewFragment.java)
  or                     .onViewCreated (AddProductOverviewFragment.java)
  at openfoodfacts.github.scrachx.openfood.fragments.AddProductOverviewFragment.getDetails (AddProductOverviewFragment.java)
  at openfoodfacts.github.scrachx.openfood.views.AddProductActivity.saveProduct (AddProductActivity.java)
  at openfoodfacts.github.scrachx.openfood.views.AddProductActivity.checkFields (AddProductActivity.java)
  at openfoodfacts.github.scrachx.openfood.views.AddProductActivity.access$1200 (AddProductActivity.java)
  or                     .lambda$onOptionsItemSelected$2$AddProductActivity (AddProductActivity.java)
  at openfoodfacts.github.scrachx.openfood.views.AddProductActivity$$Lambda$2.onClick (AddProductActivity.java)
  at com.afollestad.materialdialogs.MaterialDialog.onClick (MaterialDialog.java)
  at android.view.View.performClick (View.java:4452)
  at android.view.View$PerformClick.run (View.java:18428)
  at android.os.Handler.handleCallback (Handler.java:725)
  at android.os.Handler.dispatchMessage (Handler.java:92)
  at android.os.Looper.loop (Looper.java:176)
  at android.app.ActivityThread.main (ActivityThread.java:5365)
  at java.lang.reflect.Method.invokeNative (Method.java)
  at java.lang.reflect.Method.invoke (Method.java:511)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1102)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:869)
  at dalvik.system.NativeStart.main (NativeStart.java)

**Comment by jaindiv26** [comment] 2019-02-19 18:24
I'll try to reproduce this issue.

**Comment by serpico** [comment] 2019-02-22 13:26
I don't know if it helps but when trying again I noticed photos were sent despite the crash

see https://fr.openfoodfacts.org/produit/3760133730058/10-oeufs-frais

**Comment by sashabrava** [comment] 2019-12-24 11:19
Experienced similar issue. Activity (but not the whole app) crashes on saving new product, and the only info saved on sever is main product picture. (Without any other fields). Issue repeats randomly, haven't noticed exact steps for reproduction yet.
Android:5.1.1 
App version: 3.2.3 from Google Play Market

**Comment by teolemon** [comment] 2020-09-01 20:21
@serpico @sashabrava can you tell me if the issue is solved in the latest release ?

**Comment by sashabrava** [comment] 2020-09-10 05:57
@teolemon  I haven't noticed the issue in the latest app versions.

**Comment by teolemon** [comment] 2020-10-11 13:53
I'm going to close it, and we'll reopen if needed.

**Closed by teolemon** 2020-10-11 13:53 UTC
Labels: P1, bug, editing, fixed ?
