### ISSUE TITLE
0.7.4 App crash when product page is incomplete (drawable-hdpi-v4/error_image.png)

### ISSUE THREAD

**Issue by Hangman228** [openfoodfacts/openfoodfacts-androidapp#621] opened 2017-08-09 17:09 UTC
On Android 4.4.4, app crash when you go on ingredients page who is empty or incomplete, for example on this bar code : 3242272866053 (empty)
or this one : 7613036024358 (incomplete)

**Comment by Phyks** [comment] 2017-08-24 14:49
Same on Android 4.2.2.

**Comment by teolemon** [comment] 2017-08-27 14:39
Can you give me the version number of the app, as well as the install source ?

**Comment by Phyks** [comment] 2017-08-27 14:46
It is version 0.7.4 from [F-Droid](https://f-droid.org/packages/openfoodfacts.github.scrachx.openfood/).

**Comment by Hangman228** [comment] 2017-08-31 10:17
0.7.4 from Play Store

**Comment by Hangman228** [comment] 2017-09-08 15:22
Here is a logcat when it crash 

W/ResourceType(25156): Bad XML block: header size 18254 or total size 169478669 is larger than data size 1603
D/AndroidRuntime(25156): Shutting down VM
W/dalvikvm(25156): threadid=1: thread exiting with uncaught exception (group=0x41e7bd88)
E/AndroidRuntime(25156): FATAL EXCEPTION: main
E/AndroidRuntime(25156): Process: openfoodfacts.github.scrachx.openfood, PID: 25156
E/AndroidRuntime(25156): android.content.res.Resources$NotFoundException: File res/drawable-hdpi-v4/error_image.png from xml type xml resource ID #0x7f020064. If the resource you are trying to use is a vector resource, you may be referencing it in an unsupported way. See AppCompatDelegate.setCompatVectorFromResourcesEnabled() for more info.
E/AndroidRuntime(25156): 	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2374)
E/AndroidRuntime(25156): 	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2329)
E/AndroidRuntime(25156): 	at android.content.res.Resources.getXml(Resources.java:996)
E/AndroidRuntime(25156): 	at android.support.graphics.drawable.VectorDrawableCompat.create(Unknown Source)
E/AndroidRuntime(25156): 	at openfoodfacts.github.scrachx.openfood.views.adapters.NutrientLevelListAdapter.getView(Unknown Source)
E/AndroidRuntime(25156): 	at android.widget.AbsListView.obtainView(AbsListView.java:2255)
E/AndroidRuntime(25156): 	at android.widget.ListView.onMeasure(ListView.java:1147)
E/AndroidRuntime(25156): 	at android.view.View.measure(View.java:16628)
E/AndroidRuntime(25156): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
E/AndroidRuntime(25156): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
E/AndroidRuntime(25156): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
E/AndroidRuntime(25156): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
E/AndroidRuntime(25156): 	at android.view.View.measure(View.java:16628)
E/AndroidRuntime(25156): 	at android.support.v4.widget.NestedScrollView.measureChildWithMargins(Unknown Source)
E/AndroidRuntime(25156): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
E/AndroidRuntime(25156): 	at android.support.v4.widget.NestedScrollView.onMeasure(Unknown Source)
E/AndroidRuntime(25156): 	at android.view.View.measure(View.java:16628)
E/AndroidRuntime(25156): 	at android.support.v4.view.ViewPager.onMeasure(Unknown Source)
E/AndroidRuntime(25156): 	at android.view.View.measure(View.java:16628)
E/AndroidRuntime(25156): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
E/AndroidRuntime(25156): 	at android.support.design.widget.CoordinatorLayout.onMeasureChild(Unknown Source)
E/AndroidRuntime(25156): 	at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(Unknown Source)
E/AndroidRuntime(25156): 	at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(Unknown Source)
E/AndroidRuntime(25156): 	at android.support.design.widget.CoordinatorLayout.onMeasure(Unknown Source)
E/AndroidRuntime(25156): 	at android.view.View.measure(View.java:16628)
E/AndroidRuntime(25156): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
E/AndroidRuntime(25156): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
E/AndroidRuntime(25156): 	at android.support.v7.widget.ContentFrameLayout.onMeasure(Unknown Source)
E/AndroidRuntime(25156): 	at android.view.View.measure(View.java:16628)
E/AndroidRuntime(25156): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
E/AndroidRuntime(25156): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
E/AndroidRuntime(25156): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
E/AndroidRuntime(25156): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
E/AndroidRuntime(25156): 	at android.view.View.measure(View.java:16628)
E/AndroidRuntime(25156): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
E/AndroidRuntime(25156): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
E/AndroidRuntime(25156): 	at android.view.View.measure(View.java:16628)
E/AndroidRuntime(25156): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
E/AndroidRuntime(25156): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
E/AndroidRuntime(25156): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
E/AndroidRuntime(25156): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
E/AndroidRuntime(25156): 	at android.view.View.measure(View.java:16628)
E/AndroidRuntime(25156): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
E/AndroidRuntime(25156): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
E/AndroidRuntime(25156): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2298)
E/AndroidRuntime(25156): 	at android.view.View.measure(View.java:16628)
E/AndroidRuntime(25156): 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1916)
E/AndroidRuntime(25156): 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1113)
E/AndroidRuntime(25156): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1295)
E/AndroidRuntime(25156): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
E/AndroidRuntime(25156): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5622)
E/AndroidRuntime(25156): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
E/AndroidRuntime(25156): 	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
E/AndroidRuntime(25156): 	at android.view.
D/ActivityManager(  996): New dropbox entry: openfoodfacts.github.scrachx.openfood, data_app_crash, 5d270a37-b718-459a-beba-9a14d766e3ce
W/ActivityManager(  996):   Force finishing activity openfoodfacts.github.scrachx.openfood/.views.ProductActivity
I/CrashMonitor(24398): CrashMonitorServiceBroadcastReceiver: Forwarding intent: android.intent.action.DROPBOX_ENTRY_ADDED tag: data_app_crash
I/CrashMonitor(24398): CrashMonitorService: Service started...
W/ActivityManager(  996): Activity pause timeout for ActivityRecord{437145f0 u0 openfoodfacts.github.scrachx.openfood/.views.ProductActivity t125 f}
I/CrashMonitor(24398): CrashMonitorService: action: android.intent.action.DROPBOX_ENTRY_ADDED
W/ContextImpl(22819): Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1527 android.content.ContextWrapper.startService:494 android.content.ContextWrapper.startService:494 com.sonymobile.phoneusage.service.plugin.crashstatus.CrashStatusReceiver.onReceiveInternal:31 com.sonymobile.phoneusage.service.DeviceUsageReceiver.onReceive:27 
D/StatusBar.NetworkController( 1229): refreshViews: Data not connected!! Set no data type icon / Roaming
I/CrashMonitor(24398): CrashMonitorService: Service stopped...
I/CastDatabase( 1568): Saving the database
I/SQLiteCastStore( 1568): Saving 2 CastNetworkInfo instances, 2 CastDeviceInfo instances, 0 paired guest mode devices.
E/SQLiteCastStore( 1568): End saving paired guest mode devices





If you need more info, let me know

**Comment by Phyks** [comment] 2017-09-25 19:45
Looks like this issue is a duplicate of https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/571.

**Comment by ross-holloway94** [comment] 2017-10-23 12:04
This is an API compatibility issue, rather than resolution issue. This error is produced on API 23 but not API 25 or 26. That's all I have so far.

**Comment by teolemon** [comment] 2017-10-29 13:36
I've just updated Gradle and APIs on trunk. Can you try building it in Android Studio ? @Hangman228 @Phyks @ross-holloway94

**Comment by ross-holloway94** [comment] 2017-10-30 12:32
@teolemon same issue occurring. The newer versions are fine, it's API 23 and below that are affected.

**Comment by Rudloff** [comment] 2017-11-09 17:29
Same issue here with 0.7.4 on Android 6.0.1:
```
11-09 18:25:58.371 14828 14828 D AndroidRuntime: Shutting down VM
11-09 18:25:58.420 14828 14828 E AndroidRuntime: FATAL EXCEPTION: main
11-09 18:25:58.420 14828 14828 E AndroidRuntime: Process: openfoodfacts.github.scrachx.openfood, PID: 14828
11-09 18:25:58.420 14828 14828 E AndroidRuntime: android.content.res.Resources$NotFoundException: File res/drawable-hdpi-v4/error_image.png from xml type xml resource ID #0x7f020064
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2821)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2776)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.content.res.Resources.getXml(Resources.java:1214)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.support.graphics.drawable.VectorDrawableCompat.create(Unknown Source)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at openfoodfacts.github.scrachx.openfood.views.adapters.NutrientLevelListAdapter.getView(Unknown Source)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.widget.AbsListView.obtainView(AbsListView.java:2346)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.widget.ListView.onMeasure(ListView.java:1158)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.view.View.measure(View.java:18805)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.view.View.measure(View.java:18805)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.support.v4.widget.NestedScrollView.measureChildWithMargins(Unknown Source)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.support.v4.widget.NestedScrollView.onMeasure(Unknown Source)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.view.View.measure(View.java:18805)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.support.v4.view.ViewPager.onMeasure(Unknown Source)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.view.View.measure(View.java:18805)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.support.design.widget.CoordinatorLayout.onMeasureChild(Unknown Source)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(Unknown Source)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(Unknown Source)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.support.design.widget.CoordinatorLayout.onMeasure(Unknown Source)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.view.View.measure(View.java:18805)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.support.v7.widget.ContentFrameLayout.onMeasure(Unknown Source)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.view.View.measure(View.java:18805)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.view.View.measure(View.java:18805)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.view.View.measure(View.java:18805)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.view.View.measure(View.java:18805)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.view.View.measure(View.java:18805)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2100)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1216)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1452)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:606)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
11-09 18:25:58.420 14828 14828 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
```

**Comment by Phyks** [comment] 2017-11-19 11:00
Two extra cents on this, I can reproduce it with 0.7.3 and 0.7.4 (both from F-Droid), on Android 4.2.2. I also noticed that the splash screen is not correctly scaled on my device, not sure if this can be somehow related.

**Closed** 2018-02-17 21:29 UTC
Labels: bug
