### ISSUE TITLE
The app notification icon is not leveraged in the tooltips (seems like a regression)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#4597] opened 2022-03-23 13:28 UTC
### What
- The app notification icon is not leveraged in the tooltips (seems like a regression)

### Screenshot
![image](https://user-images.githubusercontent.com/1689815/159710183-aa1290ff-30af-46c7-991d-6d35e71bf95d.png)

**Comment by g123k** [comment] 2022-03-23 13:43
I think this is a duplicate of https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/4500
Could you try to reboot your phone and check if the icon is still wrong?

**Comment by VaiTon** [comment] 2022-03-27 01:03
Closing as a duplicate of #4500

**Closed as completed by VaiTon** 2022-03-27 01:03 UTC
