### ISSUE TITLE
Introduction for first time use 

### ISSUE THREAD

**Issue by devansh-299** [openfoodfacts/openfoodfacts-androidapp#2999] opened 2020-01-16 15:57 UTC
**Is your feature request related to a problem? Please describe.**
For a first time user the buttons on the below screen may not make sense thus providing appropriate information to first time users might be a good idea

![WhatsApp Image 2020-01-16 at 9 22 38 PM](https://user-images.githubusercontent.com/46667021/72540373-ba53c480-38a6-11ea-996d-8863f6ca78bc.jpeg)

**Describe the solution you'd like**
We can use show pop-ups  that briefly describe the use of the buttons

**Comment by teolemon** [comment] 2020-01-16 17:41
Duplicate of #2963

**Comment by teolemon** [comment] 2020-05-15 12:22
This has been fixed. Thanks @devansh-299 for the issue

**Closed by teolemon** 2020-05-15 12:22 UTC
Labels: onboarding
