### ISSUE TITLE
Nutrient name of additional nutrients is not displayed in Edit mode

### ISSUE THREAD

**Issue by JeanFred** [openfoodfacts/openfoodfacts-androidapp#4144] opened 2021-08-08 10:58 UTC
**Describe the bug**

In the Edit mode, the additional Nutrient name (“Vitamin B12” etc.) is only displayed in the edit field when it is empty. This can makes it very difficult to add nutrients, as one cannot tell anymore which ones have been entered already − the only being erasing the field. Also, I believe the app reorganises the nutrients (by alphabetical order?) so I cannot necessarily follow the order on the packaging as reference. 

**To Reproduce**
1. Edit a product
2. Nutrition facts tab
3. Scroll to additional nutrients

**Expected behavior**
I can tell which nutrient each line is.

**Actual behaviour**

There is only the text box with the amount, no indication of which nutrient this is.

**Smartphone (please complete the following information):**
 - Device: Fairphone 3+ ; Samsung Galaxy S9
 - Version 3.6.8

**Comment by TimMagee** [comment] 2021-08-09 19:50
I can confirm that I also experience this on my Moto G4 running Android 7.0.

**Comment by VaiTon** [comment] 2021-08-13 15:30
@JeanFred thank you for the report. I'm looking into it.

**Comment by VaiTon** [comment] 2021-08-13 15:36
@JeanFred I'm able to see the labels correctly. Could you attach a screenshot?

![immagine](https://user-images.githubusercontent.com/12072630/129383605-30b5e269-922f-4b9d-af12-6545bdbfc1e5.png)

**Comment by TimMagee** [comment] 2021-08-13 17:55
![Screenshot_20210813-135226](https://user-images.githubusercontent.com/11220851/129399837-8060fd74-0051-42d5-b3e4-0b1157575367.png)

The first few nutrients have there names displayed but the non-default ones do not.

**Comment by Farbklex** [comment] 2021-10-26 20:57
Looks like a duplicate to #3981

**Comment by JeanFred** [comment] 2021-10-27 08:01
> Looks like a duplicate to #3981

Correct, this appears to be a duplicate of #3981. Good catch @Farbklex

**Comment by VaiTon** [comment] 2021-10-27 11:39
Closing as duplicated of #3981

**Closed as completed by VaiTon** 2021-10-27 11:39 UTC
Labels: nutrition facts, editing, nutrition editing
