### ISSUE TITLE
java.lang.RuntimeException

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1608] opened 2018-05-22 07:36 UTC
```Yesterday, 10:04 PM on app version 51
Samsung Galaxy S6 Edge (zerolte), 3072MB RAM, Android 7.0
Report 1 of 1
java.lang.RuntimeException: 
  at android.hardware.Camera.native_getParameters (Camera.java)
  at android.hardware.Camera.getParameters (Camera.java:1952)
  at me.dm7.barcodescanner.core.CameraUtils.getCameraInstance (CameraUtils.java)
  or                     .isFlashSupported (CameraUtils.java)
  at me.dm7.barcodescanner.core.BarcodeScannerView.setFlash (BarcodeScannerView.java)
  at me.dm7.barcodescanner.core.BarcodeScannerView.setupCameraPreview (BarcodeScannerView.java)
  at me.dm7.barcodescanner.core.CameraHandlerThread$1$1.run (CameraHandlerThread.java)
  at android.os.Handler.handleCallback (Handler.java:751)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6682)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1520)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1410)
```

**Comment by jaindiv26** [comment] 2018-05-22 08:00
@teolemon This issue is the same as #443 & #377 Opened by you only on 12 Jan 17 & 2 Jan 17 Respectively. As I diagnosed this issue, I came to the conclusion that the issue is with the camera autofocus. I've tried to solve the issue but so far no luck.

**Comment by teolemon** [comment] 2018-05-22 08:21
Sorry, I tend to open a bug every time I see it.

**Comment by teolemon** [comment] 2018-05-27 07:36
https://github.com/dm77/barcodescanner/issues/294 @jaindiv26

**Comment by huzaifaiftikhar** [comment] 2018-07-15 07:04
We don't use this library anymore. Closing the issue.

**Closed by huzaifaiftikhar** 2018-07-15 07:04 UTC
Labels: camera
