### ISSUE TITLE
Fix the Service Manager

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2752] opened 2019-06-17 10:21 UTC
https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/2750/files#diff-ecfca09ce3e9da0edcf46142aa63eeaeL37

**Comment by huzaifaiftikhar** [comment] 2019-09-22 19:44
Closing as this is a duplicate of #2398

**Closed by huzaifaiftikhar** 2019-09-22 19:44 UTC
Labels: duplicate
