### ISSUE TITLE
Nutrition value saving fails

### ISSUE THREAD

**Issue by Forger7** [openfoodfacts/openfoodfacts-androidapp#3110] opened 2020-05-11 17:12 UTC
I tried entering the nutrition value with the OpenFoodFacts App 3.2.9 twice on the following product: https://world.openfoodfacts.org/product/9008700150095/happy-day-coco-ananas-rauch

The app shows it as saved, but nothing changed. 

I tried to make it work in Revision 31 and 32 but the nutrition values don’t show up.

**Comment by teolemon** [comment] 2021-04-29 11:36
Duplicate of #3919

**Closed by teolemon** 2021-04-29 11:36 UTC
Labels: P1, bug, editing, nutrition facts
